CREATE TABLE [dbo].[lu_POM_Comparison_Breakdown] (
    [OrganisationName]                 INT             NULL,
    [subsidiary_id]                    NVARCHAR (4000) NULL,
    [packaging_material]               VARCHAR (34)    NULL,
    [from_nation]                      VARCHAR (34)    NULL,
    [packaging_activity]               VARCHAR (34)    NULL,
    [packaging_class]                  VARCHAR (34)    NULL,
    [packaging_sub_material]           NVARCHAR (4000) NULL,
    [to_nation]                        VARCHAR (34)    NULL,
    [relative_move]                    VARCHAR (72)    NULL,
    [packaging_type]                   VARCHAR (34)    NULL,
    [file1_quantity_kg]                FLOAT (53)      NULL,
    [file2_quantity_kg]                FLOAT (53)      NULL,
    [file1_quantity_unit]              FLOAT (53)      NULL,
    [file2_quantity_unit]              FLOAT (53)      NULL,
    [file1_Quantity_kg_extrapolated]   FLOAT (53)      NULL,
    [file2_Quantity_kg_extrapolated]   FLOAT (53)      NULL,
    [quantity_kg_diff]                 FLOAT (53)      NOT NULL,
    [quantity_unit_diff]               FLOAT (53)      NOT NULL,
    [Quantity_kg_extrapolated_diff]    FLOAT (53)      NOT NULL,
    [Quantity_units_extrapolated_diff] FLOAT (53)      NOT NULL,
    [filename1]                        NVARCHAR (4000) NULL,
    [filename2]                        NVARCHAR (4000) NULL,
    [file1_submission_date]            DATETIME        NULL,
    [file2_submission_date]            DATETIME        NULL,
    [org_sub_type]                     VARCHAR (1)     NULL,
    [org_name]                         NVARCHAR (4000) NULL,
    [organisation_size]                NVARCHAR (4000) NULL,
    [compliance_scheme]                NVARCHAR (4000) NULL,
    [registration_type_code]           VARCHAR (1)     NULL,
    [Total_Packaging]                  VARCHAR (15)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

