CREATE TABLE [dbo].[rpt_PoM_Codes] (
    [Code] VARCHAR (7)  NOT NULL,
    [Type] VARCHAR (18) NOT NULL,
    [Text] VARCHAR (34) NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

