CREATE TABLE [dbo].[t_enrolment_report] (
    [ApprovedPerson_Email]                                  NVARCHAR (4000) NULL,
    [ApprovedPerson_FirstName]                              NVARCHAR (4000) NULL,
    [ApprovedPerson_LastName]                               NVARCHAR (4000) NULL,
    [ApprovedPerson_LastUpdatedOn]                          NVARCHAR (4000) NULL,
    [ApprovedPerson_JobTitle]                               NVARCHAR (4000) NULL,
    [ApprovedPerson_Telephone]                              NVARCHAR (4000) NULL,
    [ComplianceSchemes_Name]                                NVARCHAR (4000) NULL,
    [DelegatedPerson_Email]                                 NVARCHAR (4000) NULL,
    [DelegatedPerson_FirstName]                             NVARCHAR (4000) NULL,
    [DelegatedPerson_JobTitle]                              NVARCHAR (4000) NULL,
    [DelegatedPerson_LastName]                              NVARCHAR (4000) NULL,
    [DelegatedPerson_Telephone]                             NVARCHAR (4000) NULL,
    [DelegatedPersonEnrolment_RelationshipType]             NVARCHAR (4000) NULL,
    [DelegatedPersonEnrolment_OtherRelationshipDescription] NVARCHAR (4000) NULL,
    [Enrolment_CreatedOn_str]                               NVARCHAR (4000) NULL,
    [Enrolment_ExternalId]                                  NVARCHAR (4000) NULL,
    [Enrolment_Id]                                          INT             NULL,
    [EnrolmentStatuses_EnrolmentStatus]                     NVARCHAR (4000) NULL,
    [FromOrganisation_CompaniesHouseNumber]                 NVARCHAR (4000) NULL,
    [FromOrganisation_IsComplianceScheme]                   BIT             NULL,
    [FromOrganisation_Name]                                 NVARCHAR (4000) NULL,
    [FromOrganisation_NationName]                           NVARCHAR (4000) NULL,
    [FromOrganisation_ReferenceNumber]                      NVARCHAR (4000) NULL,
    [FromOrganisation_Type]                                 NVARCHAR (4000) NULL,
    [Organisations_Id]                                      INT             NULL,
    [ServiceRoles_Role]                                     NVARCHAR (4000) NULL,
    [ToOrganisation_IsComplianceScheme]                     BIT             NULL,
    [ToOrganisation_Name]                                   NVARCHAR (4000) NULL,
    [Status]                                                NVARCHAR (4000) NULL,
    [SelectedSchemes_IsDeleted]                             BIT             NULL,
    [Regulator_Rejection_Comments]                          NVARCHAR (4000) NULL,
    [Decision_Date]                                         NVARCHAR (4000) NULL,
    [Regulator_User_Name]                                   NVARCHAR (4000) NULL,
    [PCS_or_DP]                                             VARCHAR (17)    NOT NULL,
    [Security_Id]                                           BIGINT          NULL,
    [SecurityQuery]                                         NVARCHAR (4000) NULL,
    [ComplianceSchemes_Id]                                  INT             NULL,
    [OrganisationConnections_CreatedOn]                     NVARCHAR (4000) NULL,
    [Persons_Id]                                            INT             NULL,
    [IsLatestEnrolment]                                     VARCHAR (16)    NOT NULL,
    [CSorDP]                                                VARCHAR (15)    NOT NULL,
    [Enrolment_CreatedOn]                                   DATETIME        NULL,
    [Latest_ComplianceScheme]                               NVARCHAR (4000) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

