CREATE TABLE [dbo].[t_extract_recent_pom_org_data] (
    [Org_ID]                                                          NVARCHAR (4000) NULL,
    [Org_name]                                                        NVARCHAR (4000) NULL,
    [CH_number]                                                       NVARCHAR (4000) NOT NULL,
    [Nation_of_enrolment]                                             NVARCHAR (54)   NULL,
    [Enrolment_date_time]                                             DATETIME        NULL,
    [Enrolment_status]                                                NVARCHAR (100)  NULL,
    [Nation_of_Compliance_Scheme_regulator]                           NVARCHAR (54)   NOT NULL,
    [Packaging_data_submission_period]                                VARCHAR (21)    NOT NULL,
    [Packaging_data_first_submission_datetime]                        DATETIME        NULL,
    [Packaging_data_first_submitted_CS_or_Direct]                     NVARCHAR (4000) NOT NULL,
    [Packaging_data_first_submitted_CS_Nation]                        NVARCHAR (54)   NOT NULL,
    [Packaging_data_first_submission_status]                          NVARCHAR (4000) NOT NULL,
    [Packaging_data_first_submission_organisation_size]               NVARCHAR (4000) NULL,
    [Packaging_data_first_submission_period_code]                     NVARCHAR (4000) NULL,
    [Packaging_data_latest_submission_datetime]                       DATETIME        NULL,
    [Packaging_data_latest_submitted_CS_or_Direct]                    NVARCHAR (4000) NOT NULL,
    [Packaging_data_latest_submitted_CS_Nation]                       NVARCHAR (54)   NOT NULL,
    [Packaging_data_latest_submission_status]                         NVARCHAR (4000) NOT NULL,
    [Packaging_data_latest_submission_organisation_size]              NVARCHAR (4000) NULL,
    [Packaging_data_latest_submission_period_code]                    NVARCHAR (4000) NULL,
    [Organisation_data_submission_period]                             VARCHAR (21)    NOT NULL,
    [Organisation_data_first_submission_datetime]                     DATETIME        NULL,
    [Organisation_data_first_submitted_CS_or_Direct]                  NVARCHAR (4000) NOT NULL,
    [Organisation_data_first_submitted_CS_Nation]                     NVARCHAR (54)   NOT NULL,
    [Organisation_data_first_submission_status]                       NVARCHAR (4000) NOT NULL,
    [Organisation_data_first_submission_organisation_size]            NVARCHAR (4000) NULL,
    [Organisation_data_latest_submission_datetime]                    DATETIME        NULL,
    [Organisation_data_latest_submitted_CS_or_Direct]                 NVARCHAR (4000) NOT NULL,
    [Organisation_data_latest_submitted_CS_Nation]                    NVARCHAR (54)   NOT NULL,
    [Organisation_data_latest_submission_status]                      NVARCHAR (4000) NOT NULL,
    [Organisation_data_latest_submission_organisation_size]           NVARCHAR (4000) NULL,
    [Organisation_exists_in_most_recent_packaging_data_submission]    VARCHAR (2)     NOT NULL,
    [Organisation_exists_in_most_recent_organisation_data_submission] VARCHAR (2)     NOT NULL,
    [Organisation_visible_in_PowerBI_Packaging_reports]               VARCHAR (1)     NOT NULL,
    [Organisation_visible_in_PowerBI_Orgdata_reports]                 VARCHAR (1)     NOT NULL,
    [Single_File_Submission_Packaging]                                VARCHAR (2)     NOT NULL,
    [fps_pm_filename]                                                 NVARCHAR (4000) NULL,
    [lps_pm_filename]                                                 NVARCHAR (4000) NULL,
    [Single_File_Submission_Orgdata]                                  VARCHAR (2)     NOT NULL,
    [fos_cd_filename]                                                 NVARCHAR (4000) NULL,
    [los_cd_filename]                                                 NVARCHAR (4000) NULL,
    [Organisation_soft_deleted]                                       VARCHAR (2)     NULL,
    [Self-managed consumer waste-Aluminium]                           FLOAT (53)      NOT NULL,
    [Self-managed consumer waste-Fibre Composite]                     FLOAT (53)      NOT NULL,
    [Self-managed consumer waste-Glass]                               FLOAT (53)      NOT NULL,
    [Self-managed consumer waste-Other]                               FLOAT (53)      NOT NULL,
    [Self-managed consumer waste-Paper / Card]                        FLOAT (53)      NOT NULL,
    [Self-managed consumer waste-Plastic]                             FLOAT (53)      NOT NULL,
    [Self-managed consumer waste-Steel]                               FLOAT (53)      NOT NULL,
    [Self-managed consumer waste-Wood]                                FLOAT (53)      NOT NULL,
    [Household drinks containers-Aluminium (Kg)]                      FLOAT (53)      NOT NULL,
    [Household drinks containers-Aluminium (No.Units)]                FLOAT (53)      NOT NULL,
    [Household drinks containers-Fibre Composite (Kg)]                FLOAT (53)      NOT NULL,
    [Household drinks containers-Fibre Composite (No.Units)]          FLOAT (53)      NOT NULL,
    [Household drinks containers-Glass (Kg)]                          FLOAT (53)      NOT NULL,
    [Household drinks containers-Glass RAM (Kg)]                      FLOAT (53)      NOT NULL,
    [Household drinks containers-Glass RAM R (Kg)]                    FLOAT (53)      NOT NULL,
    [Household drinks containers-Glass RAM G (Kg)]                    FLOAT (53)      NOT NULL,
    [Household drinks containers-Glass RAM A (Kg)]                    FLOAT (53)      NOT NULL,
    [Household drinks containers-Glass RAM-M (Kg)]                    FLOAT (53)      NOT NULL,
    [Household drinks containers-Glass RAM-M R-M (Kg)]                FLOAT (53)      NOT NULL,
    [Household drinks containers-Glass RAM-M G-M (Kg)]                FLOAT (53)      NOT NULL,
    [Household drinks containers-Glass RAM-M A-M (Kg)]                FLOAT (53)      NOT NULL,
    [Household drinks containers-Glass (No.Units)]                    FLOAT (53)      NOT NULL,
    [Household drinks containers-Other (Kg)]                          FLOAT (53)      NOT NULL,
    [Household drinks containers-Other (No.Units)]                    FLOAT (53)      NOT NULL,
    [Household drinks containers-Paper / Card (Kg)]                   FLOAT (53)      NOT NULL,
    [Household drinks containers-Paper / Card (No.Units)]             FLOAT (53)      NOT NULL,
    [Household drinks containers-Plastic (Kg)]                        FLOAT (53)      NOT NULL,
    [Household drinks containers-Plastic (No.Units)]                  FLOAT (53)      NOT NULL,
    [Household drinks containers-Steel (Kg)]                          FLOAT (53)      NOT NULL,
    [Household drinks containers-Steel (No.Units)]                    FLOAT (53)      NOT NULL,
    [Household drinks containers-Wood (Kg)]                           FLOAT (53)      NOT NULL,
    [Household drinks containers-Wood (No.Units)]                     FLOAT (53)      NOT NULL,
    [Total Household packaging-Aluminium]                             FLOAT (53)      NOT NULL,
    [Total Household packaging-Aluminium RAM]                         FLOAT (53)      NOT NULL,
    [Total Household packaging-Aluminium RAM R]                       FLOAT (53)      NOT NULL,
    [Total Household packaging-Aluminium RAM G]                       FLOAT (53)      NOT NULL,
    [Total Household packaging-Aluminium RAM A]                       FLOAT (53)      NOT NULL,
    [Total Household packaging-Aluminium RAM-M]                       FLOAT (53)      NOT NULL,
    [Total Household packaging-Aluminium RAM-M R-M]                   FLOAT (53)      NOT NULL,
    [Total Household packaging-Aluminium RAM-M G-M]                   FLOAT (53)      NOT NULL,
    [Total Household packaging-Aluminium RAM-M A-M]                   FLOAT (53)      NOT NULL,
    [Total Household packaging-Fibre Composite]                       FLOAT (53)      NOT NULL,
    [Total Household packaging-Fibre Composite RAM]                   FLOAT (53)      NOT NULL,
    [Total Household packaging-Fibre Composite RAM R]                 FLOAT (53)      NOT NULL,
    [Total Household packaging-Fibre Composite RAM G]                 FLOAT (53)      NOT NULL,
    [Total Household packaging-Fibre Composite RAM A]                 FLOAT (53)      NOT NULL,
    [Total Household packaging-Fibre Composite RAM-M]                 FLOAT (53)      NOT NULL,
    [Total Household packaging-Fibre Composite RAM-M R-M]             FLOAT (53)      NOT NULL,
    [Total Household packaging-Fibre Composite RAM-M G-M]             FLOAT (53)      NOT NULL,
    [Total Household packaging-Fibre Composite RAM-M A-M]             FLOAT (53)      NOT NULL,
    [Total Household packaging-Glass]                                 FLOAT (53)      NOT NULL,
    [Total Household packaging-Glass RAM]                             FLOAT (53)      NOT NULL,
    [Total Household packaging-Glass RAM R]                           FLOAT (53)      NOT NULL,
    [Total Household packaging-Glass RAM G]                           FLOAT (53)      NOT NULL,
    [Total Household packaging-Glass RAM A]                           FLOAT (53)      NOT NULL,
    [Total Household packaging-Glass RAM-M]                           FLOAT (53)      NOT NULL,
    [Total Household packaging-Glass RAM-M R-M]                       FLOAT (53)      NOT NULL,
    [Total Household packaging-Glass RAM-M G-M]                       FLOAT (53)      NOT NULL,
    [Total Household packaging-Glass RAM-M A-M]                       FLOAT (53)      NOT NULL,
    [Total Household packaging-Other]                                 FLOAT (53)      NOT NULL,
    [Total Household packaging-Other RAM]                             FLOAT (53)      NOT NULL,
    [Total Household packaging-Other RAM R]                           FLOAT (53)      NOT NULL,
    [Total Household packaging-Other RAM G]                           FLOAT (53)      NOT NULL,
    [Total Household packaging-Other RAM A]                           FLOAT (53)      NOT NULL,
    [Total Household packaging-Other RAM-M]                           FLOAT (53)      NOT NULL,
    [Total Household packaging-Other RAM-M R-M]                       FLOAT (53)      NOT NULL,
    [Total Household packaging-Other RAM-M G-M]                       FLOAT (53)      NOT NULL,
    [Total Household packaging-Other RAM-M A-M]                       FLOAT (53)      NOT NULL,
    [Total Household packaging-Paper / Card]                          FLOAT (53)      NOT NULL,
    [Total Household packaging-Paper / Card RAM]                      FLOAT (53)      NOT NULL,
    [Total Household packaging-Paper / Card RAM R]                    FLOAT (53)      NOT NULL,
    [Total Household packaging-Paper / Card RAM G]                    FLOAT (53)      NOT NULL,
    [Total Household packaging-Paper / Card RAM A]                    FLOAT (53)      NOT NULL,
    [Total Household packaging-Paper / Card RAM-M]                    FLOAT (53)      NOT NULL,
    [Total Household packaging-Paper / Card RAM-M R-M]                FLOAT (53)      NOT NULL,
    [Total Household packaging-Paper / Card RAM-M G-M]                FLOAT (53)      NOT NULL,
    [Total Household packaging-Paper / Card RAM-M A-M]                FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic]                               FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Rigid]                         FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Flexible]                      FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic RAM]                           FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic RAM R]                         FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic RAM G]                         FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic RAM A]                         FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic RAM-M]                         FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic RAM-M R-M]                     FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic RAM-M G-M]                     FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic RAM-M A-M]                     FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Rigid RAM]                     FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Rigid RAM R]                   FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Rigid RAM G]                   FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Rigid RAM A]                   FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Rigid RAM-M]                   FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Rigid RAM-M R-M]               FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Rigid RAM-M G-M]               FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Rigid RAM-M A-M]               FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Flexible RAM]                  FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Flexible RAM R]                FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Flexible RAM G]                FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Flexible RAM A]                FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Flexible RAM-M]                FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Flexible RAM-M R-M]            FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Flexible RAM-M G-M]            FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic-Flexible RAM-M A-M]            FLOAT (53)      NOT NULL,
    [Total Household packaging-Steel]                                 FLOAT (53)      NOT NULL,
    [Total Household packaging-Steel RAM]                             FLOAT (53)      NOT NULL,
    [Total Household packaging-Steel RAM R]                           FLOAT (53)      NOT NULL,
    [Total Household packaging-Steel RAM G]                           FLOAT (53)      NOT NULL,
    [Total Household packaging-Steel RAM A]                           FLOAT (53)      NOT NULL,
    [Total Household packaging-Steel RAM-M]                           FLOAT (53)      NOT NULL,
    [Total Household packaging-Steel RAM-M R-M]                       FLOAT (53)      NOT NULL,
    [Total Household packaging-Steel RAM-M G-M]                       FLOAT (53)      NOT NULL,
    [Total Household packaging-Steel RAM-M A-M]                       FLOAT (53)      NOT NULL,
    [Total Household packaging-Wood]                                  FLOAT (53)      NOT NULL,
    [Total Household packaging-Wood RAM]                              FLOAT (53)      NOT NULL,
    [Total Household packaging-Wood RAM R]                            FLOAT (53)      NOT NULL,
    [Total Household packaging-Wood RAM G]                            FLOAT (53)      NOT NULL,
    [Total Household packaging-Wood RAM A]                            FLOAT (53)      NOT NULL,
    [Total Household packaging-Wood RAM-M]                            FLOAT (53)      NOT NULL,
    [Total Household packaging-Wood RAM-M R-M]                        FLOAT (53)      NOT NULL,
    [Total Household packaging-Wood RAM-M G-M]                        FLOAT (53)      NOT NULL,
    [Total Household packaging-Wood RAM-M A-M]                        FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Aluminium (Kg)]                  FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Aluminium (No.Units)]            FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Fibre Composite (Kg)]            FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Fibre Composite (No.Units)]      FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Glass (Kg)]                      FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Glass (No.Units)]                FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Other (Kg)]                      FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Other (No.Units)]                FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Paper / Card (Kg)]               FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Paper / Card (No.Units)]         FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Plastic (Kg)]                    FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Plastic (No.Units)]              FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Steel (Kg)]                      FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Steel (No.Units)]                FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Wood (Kg)]                       FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Wood (No.Units)]                 FLOAT (53)      NOT NULL,
    [Total Non-Household packaging-Aluminium]                         FLOAT (53)      NOT NULL,
    [Total Non-Household packaging-Fibre Composite]                   FLOAT (53)      NOT NULL,
    [Total Non-Household packaging-Glass]                             FLOAT (53)      NOT NULL,
    [Total Non-Household packaging-Other]                             FLOAT (53)      NOT NULL,
    [Total Non-Household packaging-Paper / Card]                      FLOAT (53)      NOT NULL,
    [Total Non-Household packaging-Plastic]                           FLOAT (53)      NOT NULL,
    [Total Non-Household packaging-Steel]                             FLOAT (53)      NOT NULL,
    [Total Non-Household packaging-Wood]                              FLOAT (53)      NOT NULL,
    [Self-managed organisation waste-Aluminium]                       FLOAT (53)      NOT NULL,
    [Self-managed organisation waste-Fibre Composite]                 FLOAT (53)      NOT NULL,
    [Self-managed organisation waste-Glass]                           FLOAT (53)      NOT NULL,
    [Self-managed organisation waste-Other]                           FLOAT (53)      NOT NULL,
    [Self-managed organisation waste-Paper / Card]                    FLOAT (53)      NOT NULL,
    [Self-managed organisation waste-Plastic]                         FLOAT (53)      NOT NULL,
    [Self-managed organisation waste-Steel]                           FLOAT (53)      NOT NULL,
    [Self-managed organisation waste-Wood]                            FLOAT (53)      NOT NULL,
    [Public binned-Aluminium]                                         FLOAT (53)      NOT NULL,
    [Public binned-Aluminium RAM]                                     FLOAT (53)      NOT NULL,
    [Public binned-Aluminium RAM R]                                   FLOAT (53)      NOT NULL,
    [Public binned-Aluminium RAM G]                                   FLOAT (53)      NOT NULL,
    [Public binned-Aluminium RAM A]                                   FLOAT (53)      NOT NULL,
    [Public binned-Aluminium RAM-M]                                   FLOAT (53)      NOT NULL,
    [Public binned-Aluminium RAM-M R-M]                               FLOAT (53)      NOT NULL,
    [Public binned-Aluminium RAM-M G-M]                               FLOAT (53)      NOT NULL,
    [Public binned-Aluminium RAM-M A-M]                               FLOAT (53)      NOT NULL,
    [Public binned-Fibre Composite]                                   FLOAT (53)      NOT NULL,
    [Public binned-Fibre Composite RAM]                               FLOAT (53)      NOT NULL,
    [Public binned-Fibre Composite RAM R]                             FLOAT (53)      NOT NULL,
    [Public binned-Fibre Composite RAM G]                             FLOAT (53)      NOT NULL,
    [Public binned-Fibre Composite RAM A]                             FLOAT (53)      NOT NULL,
    [Public binned-Fibre Composite RAM-M]                             FLOAT (53)      NOT NULL,
    [Public binned-Fibre Composite RAM-M R-M]                         FLOAT (53)      NOT NULL,
    [Public binned-Fibre Composite RAM-M G-M]                         FLOAT (53)      NOT NULL,
    [Public binned-Fibre Composite RAM-M A-M]                         FLOAT (53)      NOT NULL,
    [Public binned-Glass]                                             FLOAT (53)      NOT NULL,
    [Public binned-Glass RAM]                                         FLOAT (53)      NOT NULL,
    [Public binned-Glass RAM R]                                       FLOAT (53)      NOT NULL,
    [Public binned-Glass RAM G]                                       FLOAT (53)      NOT NULL,
    [Public binned-Glass RAM A]                                       FLOAT (53)      NOT NULL,
    [Public binned-Glass RAM-M]                                       FLOAT (53)      NOT NULL,
    [Public binned-Glass RAM-M R-M]                                   FLOAT (53)      NOT NULL,
    [Public binned-Glass RAM-M G-M]                                   FLOAT (53)      NOT NULL,
    [Public binned-Glass RAM-M A-M]                                   FLOAT (53)      NOT NULL,
    [Public binned-Other]                                             FLOAT (53)      NOT NULL,
    [Public binned-Other RAM]                                         FLOAT (53)      NOT NULL,
    [Public binned-Other RAM R]                                       FLOAT (53)      NOT NULL,
    [Public binned-Other RAM G]                                       FLOAT (53)      NOT NULL,
    [Public binned-Other RAM A]                                       FLOAT (53)      NOT NULL,
    [Public binned-Other RAM-M]                                       FLOAT (53)      NOT NULL,
    [Public binned-Other RAM-M R-M]                                   FLOAT (53)      NOT NULL,
    [Public binned-Other RAM-M G-M]                                   FLOAT (53)      NOT NULL,
    [Public binned-Other RAM-M A-M]                                   FLOAT (53)      NOT NULL,
    [Public binned-Paper / Card]                                      FLOAT (53)      NOT NULL,
    [Public binned-Paper / Card RAM]                                  FLOAT (53)      NOT NULL,
    [Public binned-Paper / Card RAM R]                                FLOAT (53)      NOT NULL,
    [Public binned-Paper / Card RAM G]                                FLOAT (53)      NOT NULL,
    [Public binned-Paper / Card RAM A]                                FLOAT (53)      NOT NULL,
    [Public binned-Paper / Card RAM-M]                                FLOAT (53)      NOT NULL,
    [Public binned-Paper / Card RAM-M R-M]                            FLOAT (53)      NOT NULL,
    [Public binned-Paper / Card RAM-M G-M]                            FLOAT (53)      NOT NULL,
    [Public binned-Paper / Card RAM-M A-M]                            FLOAT (53)      NOT NULL,
    [Public binned-Plastic]                                           FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Rigid]                                     FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Flexible]                                  FLOAT (53)      NOT NULL,
    [Public binned-Plastic RAM]                                       FLOAT (53)      NOT NULL,
    [Public binned-Plastic RAM R]                                     FLOAT (53)      NOT NULL,
    [Public binned-Plastic RAM G]                                     FLOAT (53)      NOT NULL,
    [Public binned-Plastic RAM A]                                     FLOAT (53)      NOT NULL,
    [Public binned-Plastic RAM-M]                                     FLOAT (53)      NOT NULL,
    [Public binned-Plastic RAM-M R-M]                                 FLOAT (53)      NOT NULL,
    [Public binned-Plastic RAM-M G-M]                                 FLOAT (53)      NOT NULL,
    [Public binned-Plastic RAM-M A-M]                                 FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Rigid RAM]                                 FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Rigid RAM R]                               FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Rigid RAM G]                               FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Rigid RAM A]                               FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Rigid RAM-M]                               FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Rigid RAM-M R-M]                           FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Rigid RAM-M G-M]                           FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Rigid RAM-M A-M]                           FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Flexible RAM]                              FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Flexible RAM R]                            FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Flexible RAM G]                            FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Flexible RAM A]                            FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Flexible RAM-M]                            FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Flexible RAM-M R-M]                        FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Flexible RAM-M G-M]                        FLOAT (53)      NOT NULL,
    [Public binned-Plastic-Flexible RAM-M A-M]                        FLOAT (53)      NOT NULL,
    [Public binned-Steel]                                             FLOAT (53)      NOT NULL,
    [Public binned-Steel RAM]                                         FLOAT (53)      NOT NULL,
    [Public binned-Steel RAM R]                                       FLOAT (53)      NOT NULL,
    [Public binned-Steel RAM G]                                       FLOAT (53)      NOT NULL,
    [Public binned-Steel RAM A]                                       FLOAT (53)      NOT NULL,
    [Public binned-Steel RAM-M]                                       FLOAT (53)      NOT NULL,
    [Public binned-Steel RAM-M R-M]                                   FLOAT (53)      NOT NULL,
    [Public binned-Steel RAM-M G-M]                                   FLOAT (53)      NOT NULL,
    [Public binned-Steel RAM-M A-M]                                   FLOAT (53)      NOT NULL,
    [Public binned-Wood]                                              FLOAT (53)      NOT NULL,
    [Public binned-Wood RAM]                                          FLOAT (53)      NOT NULL,
    [Public binned-Wood RAM R]                                        FLOAT (53)      NOT NULL,
    [Public binned-Wood RAM G]                                        FLOAT (53)      NOT NULL,
    [Public binned-Wood RAM A]                                        FLOAT (53)      NOT NULL,
    [Public binned-Wood RAM-M]                                        FLOAT (53)      NOT NULL,
    [Public binned-Wood RAM-M R-M]                                    FLOAT (53)      NOT NULL,
    [Public binned-Wood RAM-M G-M]                                    FLOAT (53)      NOT NULL,
    [Public binned-Wood RAM-M A-M]                                    FLOAT (53)      NOT NULL,
    [Reusable packaging-Aluminium]                                    FLOAT (53)      NOT NULL,
    [Reusable packaging-Fibre Composite]                              FLOAT (53)      NOT NULL,
    [Reusable packaging-Glass]                                        FLOAT (53)      NOT NULL,
    [Reusable packaging-Other]                                        FLOAT (53)      NOT NULL,
    [Reusable packaging-Paper / Card]                                 FLOAT (53)      NOT NULL,
    [Reusable packaging-Plastic]                                      FLOAT (53)      NOT NULL,
    [Reusable packaging-Steel]                                        FLOAT (53)      NOT NULL,
    [Reusable packaging-Wood]                                         FLOAT (53)      NOT NULL,
    [Small organisation packaging - all-Aluminium]                    FLOAT (53)      NOT NULL,
    [Small organisation packaging - all-Fibre Composite]              FLOAT (53)      NOT NULL,
    [Small organisation packaging - all-Glass]                        FLOAT (53)      NOT NULL,
    [Small organisation packaging - all-Other]                        FLOAT (53)      NOT NULL,
    [Small organisation packaging - all-Paper / Card]                 FLOAT (53)      NOT NULL,
    [Small organisation packaging - all-Plastic]                      FLOAT (53)      NOT NULL,
    [Small organisation packaging - all-Steel]                        FLOAT (53)      NOT NULL,
    [Small organisation packaging - all-Wood]                         FLOAT (53)      NOT NULL,
    [Transitional organisation packaging - all-Aluminium]             FLOAT (53)      NOT NULL,
    [Transitional organisation packaging - all-Fibre Composite]       FLOAT (53)      NOT NULL,
    [Transitional organisation packaging - all-Glass]                 FLOAT (53)      NOT NULL,
    [Transitional organisation packaging - all-Other]                 FLOAT (53)      NOT NULL,
    [Transitional organisation packaging - all-Paper / Card]          FLOAT (53)      NOT NULL,
    [Transitional organisation packaging - all-Plastic]               FLOAT (53)      NOT NULL,
    [Transitional organisation packaging - all-Steel]                 FLOAT (53)      NOT NULL,
    [Transitional organisation packaging - all-Wood]                  FLOAT (53)      NOT NULL,
    [Reporting_Year]                                                  INT             NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

