CREATE TABLE [dbo].[t_extract_recent_pom_org_data] (
    [Org_ID]                                                          NVARCHAR (4000) NULL,
    [Org_name]                                                        NVARCHAR (4000) NULL,
    [CH_number]                                                       NVARCHAR (4000) NOT NULL,
    [Nation_of_enrolment]                                             NVARCHAR (4000) NULL,
    [Enrolment_date_time]                                             DATETIME        NULL,
    [Enrolment_status]                                                NVARCHAR (4000) NULL,
    [Nation_of_Compliance_Scheme_regulator]                           NVARCHAR (4000) NOT NULL,
    [Packaging_data_submission_period]                                VARCHAR (21)    NOT NULL,
    [Packaging_data_first_submission_datetime]                        DATETIME        NULL,
    [Packaging_data_first_submitted_CS_or_Direct]                     NVARCHAR (4000) NOT NULL,
    [Packaging_data_first_submitted_CS_Nation]                        NVARCHAR (4000) NOT NULL,
    [Packaging_data_first_submission_status]                          NVARCHAR (4000) NOT NULL,
    [Packaging_data_first_submission_organisation_size]               NVARCHAR (4000) NULL,
    [Packaging_data_first_submission_period_code]                     NVARCHAR (4000) NULL,
    [Packaging_data_latest_submission_datetime]                       DATETIME        NULL,
    [Packaging_data_latest_submitted_CS_or_Direct]                    NVARCHAR (4000) NOT NULL,
    [Packaging_data_latest_submitted_CS_Nation]                       NVARCHAR (4000) NOT NULL,
    [Packaging_data_latest_submission_status]                         NVARCHAR (4000) NOT NULL,
    [Packaging_data_latest_submission_organisation_size]              NVARCHAR (4000) NULL,
    [Packaging_data_latest_submission_period_code]                    NVARCHAR (4000) NULL,
    [Organisation_data_submission_period]                             VARCHAR (21)    NOT NULL,
    [Organisation_data_first_submission_datetime]                     DATETIME        NULL,
    [Organisation_data_first_submitted_CS_or_Direct]                  NVARCHAR (4000) NOT NULL,
    [Organisation_data_first_submitted_CS_Nation]                     NVARCHAR (4000) NOT NULL,
    [Organisation_data_first_submission_status]                       NVARCHAR (4000) NOT NULL,
    [Organisation_data_first_submission_organisation_size]            NVARCHAR (4000) NULL,
    [Organisation_data_latest_submission_datetime]                    DATETIME        NULL,
    [Organisation_data_latest_submitted_CS_or_Direct]                 NVARCHAR (4000) NOT NULL,
    [Organisation_data_latest_submitted_CS_Nation]                    NVARCHAR (4000) NOT NULL,
    [Organisation_data_latest_submission_status]                      NVARCHAR (4000) NOT NULL,
    [Organisation_data_latest_submission_organisation_size]           NVARCHAR (4000) NULL,
    [Organisation_exists_in_most_recent_packaging_data_submission]    VARCHAR (2)     NOT NULL,
    [Organisation_exists_in_most_recent_organisation_data_submission] VARCHAR (2)     NOT NULL,
    [Organisation_visible_in_PowerBI_Packaging_reports]               VARCHAR (1)     NOT NULL,
    [Organisation_visible_in_PowerBI_Orgdata_reports]                 VARCHAR (1)     NOT NULL,
    [Single_File_Submission_Packaging]                                VARCHAR (2)     NOT NULL,
    [Single_File_Submission_Orgdata]                                  VARCHAR (2)     NOT NULL,
    [Reported_mandated_data_sets]                                     VARCHAR (1)     NOT NULL,
    [Organisation_soft_deleted]                                       VARCHAR (2)     NULL,
    [Self-managed consumer waste-Aluminium]                           FLOAT (53)      NOT NULL,
    [Self-managed consumer waste-Fibre Composite]                     FLOAT (53)      NOT NULL,
    [Self-managed consumer waste-Glass]                               FLOAT (53)      NOT NULL,
    [Self-managed consumer waste-Other]                               FLOAT (53)      NOT NULL,
    [Self-managed consumer waste-Paper / Card]                        FLOAT (53)      NOT NULL,
    [Self-managed consumer waste-Plastic]                             FLOAT (53)      NOT NULL,
    [Self-managed consumer waste-Steel]                               FLOAT (53)      NOT NULL,
    [Self-managed consumer waste-Wood]                                FLOAT (53)      NOT NULL,
    [Household drinks containers-Aluminium (Kg)]                      FLOAT (53)      NOT NULL,
    [Household drinks containers-Aluminium (No.Units)]                FLOAT (53)      NOT NULL,
    [Household drinks containers-Fibre Composite (Kg)]                FLOAT (53)      NOT NULL,
    [Household drinks containers-Fibre Composite (No.Units)]          FLOAT (53)      NOT NULL,
    [Household drinks containers-Glass (Kg)]                          FLOAT (53)      NOT NULL,
    [Household drinks containers-Glass (No.Units)]                    FLOAT (53)      NOT NULL,
    [Household drinks containers-Other (Kg)]                          FLOAT (53)      NOT NULL,
    [Household drinks containers-Other (No.Units)]                    FLOAT (53)      NOT NULL,
    [Household drinks containers-Paper / Card (Kg)]                   FLOAT (53)      NOT NULL,
    [Household drinks containers-Paper / Card (No.Units)]             FLOAT (53)      NOT NULL,
    [Household drinks containers-Plastic (Kg)]                        FLOAT (53)      NOT NULL,
    [Household drinks containers-Plastic (No.Units)]                  FLOAT (53)      NOT NULL,
    [Household drinks containers-Steel (Kg)]                          FLOAT (53)      NOT NULL,
    [Household drinks containers-Steel (No.Units)]                    FLOAT (53)      NOT NULL,
    [Household drinks containers-Wood (Kg)]                           FLOAT (53)      NOT NULL,
    [Household drinks containers-Wood (No.Units)]                     FLOAT (53)      NOT NULL,
    [Total Household packaging-Aluminium]                             FLOAT (53)      NOT NULL,
    [Total Household packaging-Fibre Composite]                       FLOAT (53)      NOT NULL,
    [Total Household packaging-Glass]                                 FLOAT (53)      NOT NULL,
    [Total Household packaging-Other]                                 FLOAT (53)      NOT NULL,
    [Total Household packaging-Paper / Card]                          FLOAT (53)      NOT NULL,
    [Total Household packaging-Plastic]                               FLOAT (53)      NOT NULL,
    [Total Household packaging-Steel]                                 FLOAT (53)      NOT NULL,
    [Total Household packaging-Wood]                                  FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Aluminium (Kg)]                  FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Aluminium (No.Units)]            FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Fibre Composite (Kg)]            FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Fibre Composite (No.Units)]      FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Glass (Kg)]                      FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Glass (No.Units)]                FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Other (Kg)]                      FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Other (No.Units)]                FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Paper / Card (Kg)]               FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Paper / Card (No.Units)]         FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Plastic (Kg)]                    FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Plastic (No.Units)]              FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Steel (Kg)]                      FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Steel (No.Units)]                FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Wood (Kg)]                       FLOAT (53)      NOT NULL,
    [Non-household drinks containers-Wood (No.Units)]                 FLOAT (53)      NOT NULL,
    [Total Non-Household packaging-Aluminium]                         FLOAT (53)      NOT NULL,
    [Total Non-Household packaging-Fibre Composite]                   FLOAT (53)      NOT NULL,
    [Total Non-Household packaging-Glass]                             FLOAT (53)      NOT NULL,
    [Total Non-Household packaging-Other]                             FLOAT (53)      NOT NULL,
    [Total Non-Household packaging-Paper / Card]                      FLOAT (53)      NOT NULL,
    [Total Non-Household packaging-Plastic]                           FLOAT (53)      NOT NULL,
    [Total Non-Household packaging-Steel]                             FLOAT (53)      NOT NULL,
    [Total Non-Household packaging-Wood]                              FLOAT (53)      NOT NULL,
    [Self-managed organisation waste-Aluminium]                       FLOAT (53)      NOT NULL,
    [Self-managed organisation waste-Fibre Composite]                 FLOAT (53)      NOT NULL,
    [Self-managed organisation waste-Glass]                           FLOAT (53)      NOT NULL,
    [Self-managed organisation waste-Other]                           FLOAT (53)      NOT NULL,
    [Self-managed organisation waste-Paper / Card]                    FLOAT (53)      NOT NULL,
    [Self-managed organisation waste-Plastic]                         FLOAT (53)      NOT NULL,
    [Self-managed organisation waste-Steel]                           FLOAT (53)      NOT NULL,
    [Self-managed organisation waste-Wood]                            FLOAT (53)      NOT NULL,
    [Public binned-Aluminium]                                         FLOAT (53)      NOT NULL,
    [Public binned-Fibre Composite]                                   FLOAT (53)      NOT NULL,
    [Public binned-Glass]                                             FLOAT (53)      NOT NULL,
    [Public binned-Other]                                             FLOAT (53)      NOT NULL,
    [Public binned-Paper / Card]                                      FLOAT (53)      NOT NULL,
    [Public binned-Plastic]                                           FLOAT (53)      NOT NULL,
    [Public binned-Steel]                                             FLOAT (53)      NOT NULL,
    [Public binned-Wood]                                              FLOAT (53)      NOT NULL,
    [Reusable packaging-Aluminium]                                    FLOAT (53)      NOT NULL,
    [Reusable packaging-Fibre Composite]                              FLOAT (53)      NOT NULL,
    [Reusable packaging-Glass]                                        FLOAT (53)      NOT NULL,
    [Reusable packaging-Other]                                        FLOAT (53)      NOT NULL,
    [Reusable packaging-Paper / Card]                                 FLOAT (53)      NOT NULL,
    [Reusable packaging-Plastic]                                      FLOAT (53)      NOT NULL,
    [Reusable packaging-Steel]                                        FLOAT (53)      NOT NULL,
    [Reusable packaging-Wood]                                         FLOAT (53)      NOT NULL,
    [Small organisation packaging - all-Aluminium]                    FLOAT (53)      NOT NULL,
    [Small organisation packaging - all-Fibre Composite]              FLOAT (53)      NOT NULL,
    [Small organisation packaging - all-Glass]                        FLOAT (53)      NOT NULL,
    [Small organisation packaging - all-Other]                        FLOAT (53)      NOT NULL,
    [Small organisation packaging - all-Paper / Card]                 FLOAT (53)      NOT NULL,
    [Small organisation packaging - all-Plastic]                      FLOAT (53)      NOT NULL,
    [Small organisation packaging - all-Steel]                        FLOAT (53)      NOT NULL,
    [Small organisation packaging - all-Wood]                         FLOAT (53)      NOT NULL,
    [Transitional organisation packaging - all-Aluminium]             FLOAT (53)      NOT NULL,
    [Transitional organisation packaging - all-Fibre Composite]       FLOAT (53)      NOT NULL,
    [Transitional organisation packaging - all-Glass]                 FLOAT (53)      NOT NULL,
    [Transitional organisation packaging - all-Other]                 FLOAT (53)      NOT NULL,
    [Transitional organisation packaging - all-Paper / Card]          FLOAT (53)      NOT NULL,
    [Transitional organisation packaging - all-Plastic]               FLOAT (53)      NOT NULL,
    [Transitional organisation packaging - all-Steel]                 FLOAT (53)      NOT NULL,
    [Transitional organisation packaging - all-Wood]                  FLOAT (53)      NOT NULL,
    [Reporting_Year]                                                  INT             NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

