CREATE TABLE [dbo].[t_FetchOrganisationRegistrationSubmissionDetails_resub]
(
    [SubmissionId] [nvarchar](4000) NULL,
    [OrganisationId] [nvarchar](4000) NULL,
    [OrganisationName] [nvarchar](4000) NULL,
    [OrganisationReference] [nvarchar](20) NULL,
    [ApplicationReferenceNumber] [nvarchar](4000) NULL,
    [RegistrationReferenceNumber] [nvarchar](4000) NULL,
    [SubmissionStatus] [nvarchar](4000) NULL,
    [StatusPendingDate] [nvarchar](4000) NULL,
    [SubmittedDateTime] [nvarchar](4000) NULL,
    [IsLateSubmission] [bit] NULL,
    [IsResubmission] [bit] NULL,
    [ResubmissionStatus] [nvarchar](4000) NULL,
    [RegistrationDate] [nvarchar](4000) NULL,
    [ResubmissionDate] [nvarchar](4000) NULL,
    [ResubmissionFileId] [nvarchar](4000) NULL,
    [SubmissionPeriod] [nvarchar](4000) NULL,
    [RelevantYear] [int] NULL,
    [IsComplianceScheme] [bit] NULL,
    [OrganisationSize] [varchar](5) NULL,
    [OrganisationType] [varchar](10) NULL,
    [NationId] [int] NULL,
    [NationCode] [varchar](6) NULL,
    [RegulatorComment] [nvarchar](4000) NULL,
    [ProducerComment] [nvarchar](4000) NULL,
    [RegulatorDecisionDate] [nvarchar](4000) NULL,
    [RegulatorResubmissionDecisionDate] [nvarchar](4000) NULL,
    [RegulatorUserId] [nvarchar](4000) NULL,
    [CompaniesHouseNumber] [nvarchar](4000) NULL,
    [BuildingName] [nvarchar](4000) NULL,
    [SubBuildingName] [nvarchar](4000) NULL,
    [BuildingNumber] [nvarchar](4000) NULL,
    [Street] [nvarchar](4000) NULL,
    [Locality] [nvarchar](4000) NULL,
    [DependentLocality] [nvarchar](4000) NULL,
    [Town] [nvarchar](4000) NULL,
    [County] [nvarchar](4000) NULL,
    [Country] [nvarchar](4000) NULL,
    [Postcode] [nvarchar](4000) NULL,
    [SubmittedUserId] [nvarchar](4000) NULL,
    [FirstName] [nvarchar](4000) NULL,
    [LastName] [nvarchar](4000) NULL,
    [Email] [nvarchar](4000) NULL,
    [Telephone] [nvarchar](4000) NULL,
    [ServiceRole] [nvarchar](100) NULL,
    [ServiceRoleId] [int] NULL,
    [IsOnlineMarketplace] [bit] NULL,
    [NumberOfSubsidiaries] [int] NOT NULL,
    [NumberOfOnlineSubsidiaries] [int] NOT NULL,
    [CompanyDetailsFileId] [nvarchar](4000) NULL,
    [CompanyDetailsFileName] [nvarchar](4000) NULL,
    [CompanyDetailsBlobName] [nvarchar](4000) NULL,
    [PartnershipFileId] [nvarchar](4000) NULL,
    [PartnershipFileName] [nvarchar](4000) NULL,
    [PartnershipBlobName] [nvarchar](4000) NULL,
    [BrandsFileId] [nvarchar](4000) NULL,
    [BrandsFileName] [nvarchar](4000) NULL,
    [BrandsBlobName] [nvarchar](4000) NULL,
    [ComplianceSchemeId] [nvarchar](4000) NULL,
    [CSId] [nvarchar](4000) NULL,
    [CSOJson] [nvarchar](max) NULL,
    [NumberOfHoldingCompaniesClosedLoopRecycling] [int] NULL,
    [NumberOfSubsidiariesClosedLoopRecycling] [int] NULL
)
WITH
(
    DISTRIBUTION = HASH ( [SubmissionId] ),
    HEAP
);
