CREATE TABLE [dbo].[t_new_Enrolment_Report] (
    [FromOrganisation_Name]                 NVARCHAR (4000) NULL,
    [ComplianceSchemes_Name]                NVARCHAR (4000) NULL,
    [Organisations_IsComplianceScheme]      BIT             NULL,
    [ComplianceSchemesName]                 NVARCHAR (4000) NULL,
    [FromOrganisation_Type]                 NVARCHAR (4000) NULL,
    [Organisation_Type]                     NVARCHAR (4000) NULL,
    [Organisations_ProducerTypeId]          INT             NULL,
    [ServiceRoles_Role]                     NVARCHAR (4000) NULL,
    [FromOrganisation_ReferenceNumber]      NVARCHAR (4000) NULL,
    [FromOrganisation_CompaniesHouseNumber] NVARCHAR (4000) NULL,
    [FromOrganisation_NationName]           NVARCHAR (4000) NULL,
    [ComplianceSchemes_NationId]            INT             NULL,
    [ApprovedPerson_FirstName]              NVARCHAR (4000) NULL,
    [ApprovedPerson_LastName]               NVARCHAR (4000) NULL,
    [ApprovedPerson_JobTitle]               NVARCHAR (4000) NULL,
    [ApprovedPerson_Telephone]              NVARCHAR (4000) NULL,
    [ApprovedPerson_Email]                  NVARCHAR (4000) NULL,
    [DelegatedPerson_FirstName]             NVARCHAR (4000) NULL,
    [DelegatedPerson_LastName]              NVARCHAR (4000) NULL,
    [DelegatedPerson_JobTitle]              NVARCHAR (4000) NULL,
    [DelegatedPerson_Email]                 NVARCHAR (4000) NULL,
    [DelegatedPerson_Telephone]             NVARCHAR (4000) NULL,
    [Enrolment_Id]                          INT             NULL,
    [Enrolment_ExternalId]                  NVARCHAR (4000) NULL,
    [Organisations_Id]                      INT             NULL,
    [Persons_Id]                            INT             NULL,
    [SelectedSchemes_IsDeleted]             BIT             NULL,
    [OrganisationConnections_CreatedOn]     NVARCHAR (4000) NULL,
    [Enrolment_CreatedOn_str]               NVARCHAR (4000) NULL,
    [Status]                                NVARCHAR (4000) NULL,
    [Regulator_Rejection_Comments]          NVARCHAR (4000) NULL,
    [Decision_Date]                         NVARCHAR (4000) NULL,
    [Regulator_User_Name]                   NVARCHAR (4000) NULL,
    [IsLatestEnrolment]                     VARCHAR (16)    NOT NULL,
    [CSorDP]                                VARCHAR (15)    NOT NULL,
    [Enrolment_CreatedOn]                   DATETIME        NULL,
    [Latest_ComplianceScheme]               NVARCHAR (4000) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

