CREATE TABLE [dbo].[t_new_enrolment_report]
(
    [FromOrganisation_Name]                                  nvarchar(4000) NULL,
    [ComplianceSchemes_Name]                                 nvarchar(4000) NULL,
    [Organisations_IsComplianceScheme]                       bit            NULL,
    [ComplianceSchemesName]                                  nvarchar(4000) NULL,
    [FromOrganisation_Type]                                  nvarchar(100)  NULL,
    [Organisation_Type]                                      nvarchar(100)  NULL,
    [Organisations_ProducerTypeId]                           int            NULL,
    [ServiceRoles_Role]                                      nvarchar(100)  NULL,
    [FromOrganisation_ReferenceNumber]                       nvarchar(4000) NULL,
    [FromOrganisation_CompaniesHouseNumber]                  nvarchar(4000) NULL,
    [FromOrganisation_NationName]                            nvarchar(54)   NULL,
    [ComplianceSchemes_NationId]                             int            NULL,
    [Compliance_Scheme_Nation]                               nvarchar(54)   NULL,
    [ApprovedPerson_FirstName]                               nvarchar(4000) NULL,
    [ApprovedPerson_LastName]                                nvarchar(4000) NULL,
    [ApprovedPerson_JobTitle]                                nvarchar(4000) NULL,
    [ApprovedPerson_Telephone]                               nvarchar(4000) NULL,
    [ApprovedPerson_Email]                                   nvarchar(4000) NULL,
    [DelegatedPerson_FirstName]                              nvarchar(4000) NULL,
    [DelegatedPerson_LastName]                               nvarchar(4000) NULL,
    [DelegatedPerson_JobTitle]                               nvarchar(4000) NULL,
    [DelegatedPerson_Email]                                  nvarchar(4000) NULL,
    [DelegatedPerson_Telephone]                              nvarchar(4000) NULL,
    [DelegatedPersonEnrolment_RelationshipType]              nvarchar(4000) NULL,
    [DelegatedPersonEnrolment_OtherRelationshipDescription]  nvarchar(4000) NULL,
    [Enrolment_Id]                                           int            NULL,
    [Enrolment_ExternalId]                                   nvarchar(4000) NULL,
    [Organisations_Id]                                       int            NULL,
    [Persons_Id]                                             int            NULL,
    [SelectedSchemes_IsDeleted]                              bit            NULL,
    [OrganisationConnections_CreatedOn]                      nvarchar(4000) NULL,
    [Enrolment_CreatedOn_str]                                nvarchar(4000) NULL,
    [Status]                                                 nvarchar(100)  NULL,
    [Regulator_Rejection_Comments]                           nvarchar(4000) NULL,
    [Decision_Date]                                          nvarchar(4000) NULL,
    [Regulator_User_Name]                                    nvarchar(4000) NULL,
    [IsLatestEnrolment]                                      varchar(16)    NOT NULL,
    [CSorDP]                                                 varchar(15)    NOT NULL,
    [Enrolment_CreatedOn]                                    datetime       NULL,
    [Latest_ComplianceScheme]                                nvarchar(4000) NULL
)
WITH
(
    CLUSTERED COLUMNSTORE INDEX,
    DISTRIBUTION = ROUND_ROBIN
);