CREATE TABLE [dbo].[t_POM_Submissions_POM_Comparison]
(
    [Org_Name]                     nvarchar(4000) NULL,
    [PCS_Or_Direct_Producer]       varchar(17)    NOT NULL,
    [Compliance_Scheme]            nvarchar(4000) NULL,
    [Org_Type]                     nvarchar(4000) NULL,
    [Org_Sub_Type]                 varchar(1)     NOT NULL,
    [organisation_size]            nvarchar(4000) NULL,
    [Submission_Date]              datetime       NULL,
    [submission_period]            varchar(34)    NULL,
    [OrganisationID]               int            NULL,
    [subsidiary_id]                nvarchar(4000) NULL,
    [CH_Number]                    nvarchar(4000) NULL,
    [Nation_Of_Enrolment]          nvarchar(4000) NULL,
    [packaging_activity]           varchar(34)    NULL,
    [packaging_type]               varchar(34)    NULL,
    [packaging_class]              varchar(34)    NULL,
    [packaging_material]           varchar(34)    NULL,
    [packaging_sub_material]       nvarchar(4000) NULL,
    [from_nation]                  varchar(34)    NULL,
    [to_nation]                    varchar(34)    NULL,
    [quantity_kg]                  float          NULL,
    [quantity_unit]                float          NULL,
    [Quantity_kg_extrapolated]     float          NULL,
    [Quantity_units_extrapolated]  float          NULL,
    [ram_rag_rating]               nvarchar(4000) NULL,
    [ToOrganisation_NationName]    nvarchar(4000) NULL,
    [Nation]                       nvarchar(4000) NULL,
    [FromOrganisation_NationName]  nvarchar(4000) NULL,
    [FileName]                     nvarchar(4000) NULL,
    [ServiceRoles_Role]            varchar(1)     NOT NULL,
    [SubmittedBy]                  nvarchar(4000) NOT NULL,
    [filetype]                     nvarchar(4000) NULL,
    [Users_Email]                  varchar(1)     NOT NULL,
    [Persons_Email]                varchar(1)     NOT NULL,
    [metafile]                     nvarchar(4000) NULL,
    [JOINFIELD]                    nvarchar(4000) NULL,
    [relative_move]                varchar(72)    NULL,
    [SubmtterEmail]                nvarchar(4000) NULL,
    [ServiceRoles_Name]            nvarchar(100)  NULL,
    [OriginalFileName]             nvarchar(4000) NULL,
    [data_type]                    varchar(8)     NOT NULL,
    [registration_type_code]       varchar(1)     NOT NULL,
    [Regulator_Status]             nvarchar(4000) NULL
)
WITH
(
    CLUSTERED COLUMNSTORE INDEX,
    DISTRIBUTION = ROUND_ROBIN
);