CREATE TABLE [dbo].[t_submitted_pom_org_file_status] (
    [SubmissionId]                                      NVARCHAR (4000) NULL,
    [RegistrationSetId]                                 NVARCHAR (4000) NULL,
    [OrganisationId]                                    NVARCHAR (4000) NULL,
    [FileName]                                          NVARCHAR (4000) NULL,
    [FileType]                                          NVARCHAR (4000) NULL,
    [OriginalFileName]                                  NVARCHAR (4000) NULL,
    [TargetDirectoryName]                               NVARCHAR (4000) NULL,
    [Decision_Date]                                     NVARCHAR (4000) NULL,
    [Regulator_Status]                                  NVARCHAR (4000) NULL,
    [RegulatorDecision]                                 VARCHAR (1)     NOT NULL,
    [Regulator_User_Name]                               NVARCHAR (4000) NOT NULL,
    [Regulator_Rejection_Comments]                      NVARCHAR (4000) NULL,
    [RejectionComments]                                 VARCHAR (1)     NOT NULL,
    [Type]                                              NVARCHAR (4000) NULL,
    [UserId]                                            NVARCHAR (4000) NULL,
    [RowNumber]                                         BIGINT          NULL,
    [Created]                                           NVARCHAR (4000) NULL,
    [Application_submitted_ts]                          NVARCHAR (4000) NULL,
    [RegistrationType]                                  INT             NULL,
    [SubmissionPeriod]                                  NVARCHAR (4000) NULL,
    [ApplicationReferenceNo]                            NVARCHAR (4000) NULL,
    [registrationreferencenumber]                       NVARCHAR (4000) NULL,
    [Original_Regulator_Status]                         NVARCHAR (4000) NULL,
    [SubmissionType]                                    NVARCHAR (4000) NULL,
    [IsResubmission_identifier]                         BIT             NOT NULL,
    [Is_resubmitted_POM_identifier]                     INT             NOT NULL,
    [cfm_FileId]                                        NVARCHAR (4000) NULL,
    [FileId]                                            NVARCHAR (4000) NULL,
    [fileid_new]                                        NVARCHAR (4000) NULL,
    [submitted_Fileid]                                  NVARCHAR (4000) NULL,
    [SubmissionEventId_of_submitted_record]             NVARCHAR (4000) NULL,
    [app_submitted_Fileid]                              NVARCHAR (4000) NULL,
    [SubmissionEventId_of_application_submitted_record] NVARCHAR (4000) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([FileName]));

