CREATE TABLE [apps].[OrgRegistrationsSummaries] (
    [SubmissionId]                NVARCHAR (4000) NULL,
    [OrganisationId]              NVARCHAR (4000) NULL,
    [OrganisationInternalId]      INT             NULL,
    [OrganisationName]            NVARCHAR (4000) NULL,
    [UploadedOrganisationName]    NVARCHAR (4000) NULL,
    [OrganisationReference]       NVARCHAR (4000) NULL,
    [SubmittedUserId]             NVARCHAR (4000) NULL,
    [IsComplianceScheme]          INT             NOT NULL,
    [OrganisationType]            VARCHAR (10)    NULL,
    [ProducerSize]                VARCHAR (5)     NULL,
    [ApplicationReferenceNumber]  NVARCHAR (4000) NULL,
    [RegistrationReferenceNumber] NVARCHAR (4000) NULL,
    [SubmittedDateTime]           NVARCHAR (4000) NULL,
    [FirstSubmissionDate]         NVARCHAR (4000) NULL,
    [RegistrationDate]            NVARCHAR (4000) NULL,
    [IsResubmission]              INT             NOT NULL,
    [ResubmissionDate]            NVARCHAR (4000) NULL,
    [RelevantYear]                INT             NULL,
    [SubmissionPeriod]            NVARCHAR (4000) NULL,
    [IsLateSubmission]            BIT             NULL,
    [SubmissionStatus]            NVARCHAR (4000) NOT NULL,
    [ResubmissionStatus]          NVARCHAR (4000) NULL,
    [ResubmissionDecisionDate]    NVARCHAR (4000) NULL,
    [RegulatorDecisionDate]       NVARCHAR (4000) NULL,
    [StatusPendingDate]           NVARCHAR (4000) NULL,
    [NationId]                    INT             NULL,
    [NationCode]                  VARCHAR (6)     NULL,
    [ComplianceSchemeId]          NVARCHAR (4000) NULL,
    [ProducerComment]             NVARCHAR (4000) NULL,
    [RegulatorComment]            NVARCHAR (4000) NULL,
    [FileId]                      NVARCHAR (4000) NULL,
    [ResubmissionComment]         NVARCHAR (4000) NULL,
    [ResubmittedUserId]           NVARCHAR (4000) NULL,
    [ProducerUserId]              NVARCHAR (4000) NULL,
    [RegulatorUserId]             NVARCHAR (4000) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

