CREATE TABLE [apps].[RegistrationsSummaries] (
    [SubmissionId]              NVARCHAR (4000) NULL,
    [OrganisationId]            NVARCHAR (4000) NULL,
    [ComplianceSchemeId]        NVARCHAR (4000) NULL,
    [OrganisationName]          NVARCHAR (4000) NULL,
    [OrganisationReference]     NVARCHAR (4000) NULL,
    [CompaniesHouseNumber]      NVARCHAR (4000) NULL,
    [SubBuildingName]           NVARCHAR (4000) NULL,
    [BuildingName]              NVARCHAR (4000) NULL,
    [BuildingNumber]            NVARCHAR (4000) NULL,
    [Street]                    NVARCHAR (4000) NULL,
    [Locality]                  NVARCHAR (4000) NULL,
    [DependentLocality]         NVARCHAR (4000) NULL,
    [Town]                      NVARCHAR (4000) NULL,
    [County]                    NVARCHAR (4000) NULL,
    [Country]                   NVARCHAR (4000) NULL,
    [Postcode]                  NVARCHAR (4000) NULL,
    [OrganisationType]          NVARCHAR (4000) NULL,
    [ProducerType]              NVARCHAR (4000) NULL,
    [UserId]                    NVARCHAR (4000) NULL,
    [FirstName]                 NVARCHAR (4000) NULL,
    [LastName]                  NVARCHAR (4000) NULL,
    [Email]                     NVARCHAR (4000) NULL,
    [Telephone]                 NVARCHAR (4000) NULL,
    [ServiceRole]               NVARCHAR (4000) NULL,
    [CompanyDetailsFileId]      NVARCHAR (4000) NULL,
    [CompanyDetailsFileName]    NVARCHAR (4000) NULL,
    [CompanyDetailsBlobName]    NVARCHAR (4000) NULL,
    [PartnershipFileId]         NVARCHAR (4000) NULL,
    [PartnershipFileName]       NVARCHAR (4000) NULL,
    [PartnershipBlobName]       NVARCHAR (4000) NULL,
    [BrandsFileId]              NVARCHAR (4000) NULL,
    [BrandsFileName]            NVARCHAR (4000) NULL,
    [BrandsBlobName]            NVARCHAR (4000) NULL,
    [SubmissionPeriod]          NVARCHAR (4000) NULL,
    [RegistrationDate]          NVARCHAR (4000) NULL,
    [Decision]                  NVARCHAR (4000) NULL,
    [Comments]                  NVARCHAR (4000) NULL,
    [IsResubmission]            BIT             NULL,
    [PreviousRejectionComments] NVARCHAR (4000) NULL,
    [NationId]                  INT             NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([SubmissionId]));

