/* CREATE workload groups */

CREATE WORKLOAD GROUP WG_ELT_Pipeline
WITH
(
    MIN_PERCENTAGE_RESOURCE = 20,
    CAP_PERCENTAGE_RESOURCE = 90,
    REQUEST_MIN_RESOURCE_GRANT_PERCENT = 10,
    REQUEST_MAX_RESOURCE_GRANT_PERCENT = 45,
    IMPORTANCE = NORMAL,
    QUERY_WAIT_TIMEOUT_SEC = 3600
);

CREATE WORKLOAD GROUP WG_FrontEnd_Query
WITH
(
    MIN_PERCENTAGE_RESOURCE = 10,
    CAP_PERCENTAGE_RESOURCE = 75,
    REQUEST_MIN_RESOURCE_GRANT_PERCENT = 5,
    REQUEST_MAX_RESOURCE_GRANT_PERCENT = 20,
    IMPORTANCE = HIGH,
    QUERY_WAIT_TIMEOUT_SEC = 300
);

/* CREATE classifiers */

CREATE WORKLOAD CLASSIFIER WGC_ELT_Pipeline_synrpduser
WITH
(
    WORKLOAD_GROUP = 'WG_ELT_Pipeline',
    MEMBERNAME = 'synrpduser'
);

CREATE WORKLOAD CLASSIFIER WGC_FrontEnd_App
WITH
(
    WORKLOAD_GROUP = 'WG_FrontEnd_Query',
    MEMBERNAME = 'PRDRWDWEBWA1415'
);