CREATE VIEW [rpd].[files_processed]
AS SELECT distinct 
 [SubmissionId]
,[FileId]
,[UserId]
,[BlobName]
,[BlobContainerName]
,[FileType]
,[Created]
,[OriginalFileName]
,[OrganisationId]
,[DataSourceType]
,[SubmissionPeriod]
,[IsSubmitted]
,[SubmissionType]
,[ComplianceSchemeId]
,[TargetDirectoryName]
,[TargetContainerName]
,[SourceContainerName]
,[FileName]
 FROM [rpd].[cosmos_file_metadata]
 Where FileName Not In (select distinct FileName from rpd.error_files_not_processed);