CREATE PROCEDURE [dbo].[sp_FetchOrganisationRegistrationSubmissionDetails_resub]
    @SubmissionId [nvarchar](36)
AS

BEGIN
	SET NOCOUNT ON;

	select o.SubmissionId,
           o.OrganisationId,
           o.OrganisationName,
           o.OrganisationReference,
           o.ApplicationReferenceNumber,
           o.RegistrationReferenceNumber,
           o.SubmissionStatus,
           o.StatusPendingDate,
           o.SubmittedDateTime,
           o.IsLateSubmission,
           o.IsResubmission,
           o.ResubmissionStatus,
           o.RegistrationDate,
           o.ResubmissionDate,
           o.ResubmissionFileId,
           o.SubmissionPeriod,
           o.RelevantYear,
           o.IsComplianceScheme,
           o.OrganisationSize,
           o.OrganisationType,
           o.NationId,
           o.NationCode,
           o.RegulatorComment,
           o.ProducerComment,
           o.RegulatorDecisionDate,
           o.RegulatorResubmissionDecisionDate,
           o.RegulatorUserId,
           o.CompaniesHouseNumber,
           o.BuildingName,
           o.SubBuildingName,
           o.BuildingNumber,
           o.Street,
           o.Locality,
           o.DependentLocality,
           o.Town,
           o.County,
           o.Country,
           o.Postcode,
           o.SubmittedUserId,
           o.FirstName,
           o.LastName,
           o.Email,
           o.Telephone,
           o.ServiceRole,
           o.ServiceRoleId,
           o.IsOnlineMarketplace,
           o.NumberOfSubsidiaries,
           o.NumberOfOnlineSubsidiaries,
           o.CompanyDetailsFileId,
           o.CompanyDetailsFileName,
           o.CompanyDetailsBlobName,
           o.PartnershipFileId,
           o.PartnershipFileName,
           o.PartnershipBlobName,
           o.BrandsFileId,
           o.BrandsFileName,
           o.BrandsBlobName,
           o.ComplianceSchemeId,
           o.CSId,
           o.CSOJson,
           IsNull(ORS.RegistrationJourney, s.RegistrationJourney) AS RegistrationJourney,
           cast(0 as bit) AS IsClosedLoopRecycler,  -- DEPRECATION: for backwards compatibility during the release. Remove after https://eaflood.atlassian.net/wiki/spaces/EDIA/pages/6524338439/Release+17.13+Release+EPR+Common+Data+API-+Release+Runbook
           o.NumberOfHoldingCompaniesClosedLoopRecycling,
           o.NumberOfSubsidiariesClosedLoopRecycling
    FROM dbo.t_FetchOrganisationRegistrationSubmissionDetails_resub o
             LEFT JOIN apps.OrgRegistrationsSummaries ors ON ors.SubmissionId = o.Submissionid
             JOIN apps.Submissions s ON s.SubmissionId = o.SubmissionId
    WHERE o.SubmissionId = @SubmissionId;
END
