CREATE TABLE [rpd].[Prn] (
    [Id]                        INT             NULL,
    [ExternalId]                NVARCHAR (4000) NULL,
    [PrnNumber]                 NVARCHAR (4000) NULL,
    [OrganisationId]            NVARCHAR (4000) NULL,
    [OrganisationName]          NVARCHAR (4000) NULL,
    [ProducerAgency]            NVARCHAR (4000) NULL,
    [ReprocessorExporterAgency] NVARCHAR (4000) NULL,
    [PrnStatusId]               INT             NULL,
    [TonnageValue]              INT             NULL,
    [MaterialName]              NVARCHAR (4000) NULL,
    [IssuerNotes]               NVARCHAR (4000) NULL,
    [IssuerReference]           NVARCHAR (4000) NULL,
    [PrnSignatory]              NVARCHAR (4000) NULL,
    [PrnSignatoryPosition]      NVARCHAR (4000) NULL,
    [Signature]                 NVARCHAR (4000) NULL,
    [IssueDate]                 DATETIME2 (7)   NULL,
    [ProcessToBeUsed]           NVARCHAR (4000) NULL,
    [DecemberWaste]             BIT             NULL,
    [StatusUpdatedOn]           DATETIME2 (7)   NULL,
    [IssuedByOrg]               NVARCHAR (4000) NULL,
    [AccreditationNumber]       NVARCHAR (4000) NULL,
    [ReprocessingSite]          NVARCHAR (4000) NULL,
    [AccreditationYear]         NVARCHAR (4000) NULL,
    [ObligationYear]            NVARCHAR (4000) NULL,
    [PackagingProducer]         NVARCHAR (4000) NULL,
    [CreatedBy]                 NVARCHAR (4000) NULL,
    [CreatedOn]                 DATETIME2 (7)   NULL,
    [LastUpdatedBy]             NVARCHAR (4000) NULL,
    [LastUpdatedDate]           DATETIME2 (7)   NULL,
    [IsExport]                  BIT             NULL,
    [load_ts]                   DATETIME2 (7)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

